service: nest
image: hugeen/nest

servers:
  web:
    - IP_DEDIE

proxy:
  ssl: true
  host: perkycrow.com

registry:
  username: hugeen
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - NEST_DATABASE_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true

ssh:
  user: debian

volumes:
  - "nest_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"
